name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Run lint
      run: yarn lint

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn deploy --name="criceta bot" --email=tomoki.mizogami@gmail.com
